### ISSUE TITLE
'broccoli-babel-transpiler is opting out of caching' warning

### ISSUE THREAD

**Issue by cesarizu** [ember-cli/babel-plugin-feature-flags#13]
When running an ember-cli app I see the following warning:

```
WARNING: broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `function (babel) {
    var t = babel.types;

    return new babel.Transformer('babel-plugin-feature-flags', {
      CallExpression: function(node, parent, scope, file) {
        var callee = this.get('callee');
        if (callee.referencesImport(options.import.module, options.import.name)) {
          var featureName = getFeatureName(node);
          if (featureName in options.features) {
            var value = options.features[featureName];

            if (typeof value === 'boolean') {
              this.replaceWith(t.literal(value));
            }
          } else {
            file.log.error("An unknown feature '" + featureName + "'' was encountered");
          }
        }
      }
    });
  }`.
```

I suspect this is making the builds slower, is there something I can do about this?

P.S. With some guidance I could prepare a PR to fix this issue.

**Comment by Turbo87** [comment]
this should be resolved by https://github.com/ember-cli/babel-plugin-feature-flags/pull/12 already. try to run `npm ls babel-plugin-feature-flags` to see if you have an outdated dependency somewhere.

**Comment by cesarizu** [comment]
Thank you. I had an outdated dependency that was using this plugin.

**Comment by tinyweasel** [comment]
This is happening to me too, and I'm getting 'empty' for the npm command. It also doesn't seem to be happening anyone else on my team, and we should (_should_) have the same dependencies.

**Comment by kanongil** [comment]
I'm seeing this after updating to ember-cli@2.15.1 from 2.14, and have no idea on how to fix it.

**Comment by Mithrilhall** [comment]
I'm seeing this as well after upgrading Ember to 2.15.1

> X@X ~/source-git/web-content-uploader $ npm ls babel-plugin-feature-flags
web-content-uploader-electron@0.0.0 /home/machine/source-git/web-content-uploader
└─┬ ember-data@2.15.0
  └── babel-plugin-feature-flags@0.3.1

**Comment by XaserAcheron** [comment]
Same here --I just upgraded  `ember` and `ember-cli` to 2.15 without issue, but I'm seeing the same thing after updating `ember-data`. The app still builds and works just fine, for the record.

Since this is a closed issue, this is probably "open a new one" territory. Should that be done on this repo or the main `ember-cli` one, though?
