### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/babel-plugin-feature-flags#5]
As mentioned in https://github.com/ember-cli/ember-cli/issues/5015 this plugin should be ported to the Babel 6 plugin API.

I would have started to port it but then I saw that https://github.com/ember-cli/babel-plugin-feature-flags/pull/4 has rewritten a lot of the code. Should I port the old codebase or wait until https://github.com/ember-cli/babel-plugin-feature-flags/pull/4 is merged?

/cc @mmun @stefanpenner

**Comment by mmun** [comment]
Sweet! Glad we're moving to Babel 6! I merged the other PR -- feel free to rewrite.
